// Action Types
export const TODOS_REQUESTING_SUCCESS = 'TODOS_REQUESTING_SUCCESS'
export const TODOS_REQUESTING_ERROR = 'TODOS_REQUESTING_ERROR'
export const TODOS_REQUESTING = 'TODOS_REQUESTING'
export const TODO_COMPLETE = 'TODO_COMPLETE'
export const TODO_ADD = 'ADD_TODO'
export const TODO_ADD_REQUEST_SUCCESS = 'TODO_ADD_REQUEST_SUCCESS'
export const TODO_ADD_REQUEST_ERROR = 'TODO_ADD_REQUEST_ERROR'
